server:
  port: ${PORT:8082}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  security:
    user:
      name: username
      password: secret
      roles: USER
acquirer:
  base-aut-url: ${URL_AUTH}